name: 'wildfire_mapping'
channels:
    - conda-forge
dependencies:
    - cartopy
    - fiona
    - flake8>=3.5.0
    - gdal
    - geopandas
    - ipykernel>=4.8.2
    - joblib
    - jupyter
    - libgdal
    - matplotlib>=2.2.2
    - numpy>=1.14.5
    - pandas>=0.23.4
    - pyarrow
    - pysal
    - python-dateutil>=2.7.3
    - python-language-server>=0.21.2
    - python-snappy>=0.5.2
    - python>=3.6
    - rasterio
    - requests
    - rtree
    - scipy
    - seaborn>=0.8.1
    - shapely
    - statsmodels>=0.9.0
    - tabulate>=0.8.2
    - xarray
    - yapf>=0.22.0
